version: '3.8'

services:
  proto_tasker_app:
    image: protot
    environment:
      - PROTOT_GRPC_PORT=44880
      - PROTOT_REDIS_HOST="redis://redis/"
    networks:
      - proto_tasker_net
    depends_on:
      - redis
    ports:
      - "44880:44880"
      - "9091:9091"

  prom:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - proto_tasker_net
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    networks:
      - proto_tasker_net
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
  
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - proto_tasker_net
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

networks:
  proto_tasker_net:
    driver: bridge
