[package]
name = "protot_examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
protot = { path = "../" }
tokio = "1.32.0"
tonic = "0.10.0"
